/* global i18nextko, ko */

i18nextko.init({
  "en": {
    "translation": {
      "openevse": "OpenEVSE",
      "loading": "Loading, please wait... ",
      "language": "Language",
      "system": "System",
      "services": "Services",
      "vehicle": "Vehicle",
      "saving": "Saving",
      "saved": "Saved",
      "save": "Save",
      "wifisetup": "Wifi Setup",
      "mode": "Mode:",
      "ip": "IP Address",
      "sfpackets": "Successful packets:",
      "rapipackets": "RAPI packets:",
      "network": "Network",
      "rssi": "RSSI dBm",
      "changewifi": "Change WiFi network",
      "of": " of ",
      "connect2net": "Connect to network:",
      "poffaccesspoint": "Turn off Access Point",
      "scanning": "Scanning...",
      "ssid": "SSID:",
      "passkey": "Passkey",
      "showpass": "Show password",
      "connect": "Connect",
      "connecting": "Connecting to WIFI Network...",
      "administration": "Administration",
      "username": "Username:",
      "15max": "15 characters max",
      "31max": "31 characters max",
      "password": "Password:",
      "showpassword": "Show password",
      "httpauth": "Web interface HTTP authentication.",
      "wififirmware": "WiFi Firmware",
      "version": "Version: ",
      "update": "Update",
      "updating": "Updating...",
      "error": "Error",
      "complete": "Firmware update completed ok",
      "restart": "Restart",
      "restarting": "Restarting...",
      "reset": "Factory Reset",
      "resetting": "Resetting...",
      "advsettings": "Advanced Settings",
      "hostname": "Hostname:",
      "ntpserver": "NTP Server:",
      "rfid": "RFID",
      "enabled": "Enabled",
      "rfidnotfound": "Reader not found",
      "rfidregistered": "Registered tags",
      "remove": "Remove",
      "rfidclear": "Clear Tags",
      "rfidmanage": "Manage scanned tags",
      "rfidscan": "Scan",
      "rfidplace": "Place your RFID tag on the scanner... ",
      "waiting": "Waiting",
      "rfidscanned": "Tag scanned successfully!",
      "rfiduid": "UID",
      "rfidalregistered": "The tag is already registered",
      "rfidnotregistered": "The tag is not registered",
      "rfidregister": "Register tag",
      "rfidremove": "Remove tag",
      "devmode": "Developer Mode",
      "serialconsoles": "Serial Consoles",
      "debug": "Debug",
      "emoncms": "Energy Monitoring",
      "emoncmsenable": "Enable Emoncms",
      "emoncmsserver": "Emoncms Server*:",
      "emoncmsnode": "Emoncms Node*:",
      "emoncmsapi": "Emoncms write-apikey*:",
      "emoncmsssltitle": "Emoncms SSL SHA-1 Fingerprint (optional):",
      "emoncmshttps": "HTTPS will be enabled if present e.g:",
      "connected": "Connected:",
      "yes": "yes",
      "no": "no",
      "emoncmssuccess": "Successful posts:",
      "mqtt": "MQTT",
      "mqttenable": "Enable MQTT",
      "mqttstatuspub": "Status published to:",
      "mqttstatusval": "{base-topic}/{status} value",
      "mqttrapi": "RAPI over MQTT is deprecated. Use /claim or /override API",
      "host": "Host*:",
      "port": "Port*:",
      "rejectcert": "Reject self-signed certificates:",
      "warning": "Warning!!",
      "mqttcerts": "Certificate validation is disabled, although the connection to MQTT server will be encrypted the connection is still vulnerable to man-in-the-middle attacks.",
      "blank": " blank - no authentication",
      "basetopic": "Base-topic*:",
      "retain": "Retain published data",
      "voltagetop": "Voltage topic:",
      "voltagedesc": "Voltage MQTT topic to improve power calculations",
      "shaper": "Current Shaper",
      "shaperenable": "Enable Current Shaper",
      "shaperdesc": "Throttle charge current following your house loads to prevent exceeding what your energy plan can deliver.<br>",
      "shapermaxpow": "Max power allowed (in W):",
      "shaperlivepow": "Live power load MQTT Topic (in W):",
      "ohm": "OhmConnect",
      "ohmenable": "Enable OhmConnect",
      "ohmclick": "Click Here to Join",
      "ohmdesc": "OhmConnect monitors real-time conditions on the electricity grid. When dirty and unsustainable power plants turn on, our users receive a notification to save energy.",
      "ohmhour": "Ohm Hour:",
      "ohmkey": "Ohm Key:",
      "ohmusa": "USA - California only",
      "ohmkeydesc": "Ohm Key can be obtained by logging in to OhmConnect, enter Settings and locate the link in \"Open Source Projects\".<br/>Example: https://login.ohmconnect.com/verify-ohm-hour/OpnEoVse",
      "key": "Key:",
      "divert": "Solar PV divert",
      "divertenable": "enable Solar PV Divert",
      "nomqtt": "MQTT not enabled.",
      "nomqttdesc": "You need to enable MQTT on the <a href=\"#services\">Services</a> tab.",
      "divertnomqttdesc": "Solar PV Divert requires an SolarPV-gen or Grid (+I/-E) feed to be delivered via MQTT.",
      "divertdesc1": "Dynamically adjust charge rate based on solar PV generation or excess power (grid export).",
      "divertdesc2": "If only solar PV feed available: charge rate is modulated based on <b>solar PV generation.</b>",
      "divertdesc3": "If grid +I/-E (positive Import / negative Export) feed is available: charge rate will be modulated by available  <b>excess power.</b>",
      "divertdesc4": "If EVSE is sleeping: charging will begin when solar PV / excess power > min charge rate.",
      "divertdesc5": "Charging will pause if the excess power drops below the min charge rate for a period of time.",
      "divertnote": "Note: It's assumed that EVSE power is included in the grid feed",
      "divertsolar": "Solar:",
      "divertgrid": "Grid Import/Export:",
      "chargerate": "Charge rate:",
      "divertfeed": "Feed*:",
      "divertsolar2": "SolarPV-gen",
      "divertgrid2": "Grid (+I/-E)",
      "divertsolar2desc": "Solar PV MQTT topic to modulate charge rate based on solar",
      "divertgrid2desc": "Grid (+I/-E) MQTT topic to modulate charge rate based on <b>excess power</b>",
      "divertpvpratio": "Required PV power ratio:",
      "divertpvpratiodesc": "The fraction of PV current that suffices to start charging or increment current",
      "divertsmoothatt": "Divert smoothing attack:",
      "divertsmoothattdesc": "The amount of the new feed value to add to the divert available power rolling average",
      "divertsmoothdec": "Divert smoothing decay:",
      "divertsmoothdecdesc": "The amount of the new feed value to remove to the divert available power rolling average ",
      "divertmintime": "Minimum charge time:",
      "divertmintimedesc": "The minimum amount of time (seconds) to charge the car once enabled via the Solar PV divert. This can help minimise wear and tear on the EVSE.",
      "divertwait": "Waiting for solar",
      "divertcharge": "Charging from solar",
      "ocpp": "OCPP 1.6",
      "ocppenable": "Enable OCPP",
      "ocppserver": "Central System URL*:",
      "ocppserverhint": "e.g.: wss://ocpp.example.com/steve/websocket/CentralSystemService",
      "ocppid": "Charge Box ID*:",
      "ocppacccont": "Access control:",
      "ocppsuspend": "OCPP can suspend EVSE",
      "ocppenergize": "OCPP can energize plug",
      "ocppauthkey": "WebSocket Key (Security Profile 2):",
      "ocppauth": "Charge Authorization:",
      "ocppauthauto": "Authorize automatically",
      "ocppauthoffline": "Skip Authorization when offline",
      "evseerror": "EVSE Error",
      "evseerrordesc1": "OpenEVSE not responding or not connected",
      "status": "Status",
      "current": "Current",
      "temp": "Temp",
      "energy": "Energy",
      "elapsed": "Elapsed",
      "evnocon": "EV not connected",
      "evcon": "EV connected",
      "active": "Active:",
      "voltage": "Voltage:",
      "avcur": "Available Current:",
      "smcur": "Smoothed Current:",
      "mintimerem": "Min time remaining:",
      "curevent": "Current Event:",
      "nxtevent": "Next Event:",
      "modenml": "Normal (fast)",
      "modeeco": "Eco (PV divert)",
      "chargeopt": "Charge Options",
      "manoverride": "Manual Override",
      "start": "Start",
      "pause": "Pause",
      "stop": "Stop",
      "clear": "Clear",
      "timelimit": "Time Limit:",
      "energylimit": "Energy Limit:",
      "timer": "Timer:",
      "delaydesc1": "A random delay of up to +/-",
      "delaydesc2": "minutes will be applied to the start time to help prevent sudden load increases on the grid.",
      "delayadj": "Random start adjust:",
      "seconds": "seconds",
      "set": "Set",
      "cancel": "Cancel",
      "starting": "Starting",
      "session": "This session:",
      "total": "Total:",
      "sensorval": "Sensor Values",
      "sensor": "Sensor",
      "value": "Value",
      "pilot": "Pilot:",
      "curnow": "Current Now:",
      "setup": "Setup",
      "rtc": "Time: No RTC detected",
      "time": "Time",
      "timezone": "Time zone:",
      "settimefrom": "Set time from",
      "settime": "Set time",
      "manual": "Manual",
      "browser": "Browser",
      "ntp": "NTP",
      "servicelev": "Service Level:",
      "maxcur": "Max Current:",
      "name": "Name",
      "level": "Level",
      "min": "Minimum:",
      "max": "Maximum:",
      "ssrscale": "Sensor Scale:",
      "ssroff": "Sensor Offset:",
      "safety": "Safety",
      "safetydesc": "Hardware safety checks. Enable dev mode (System > Developer Mode) to enable/disable or use the physical LCD + menu button.",
      "safetywarn": "Not all the safety tests are enabled, please take extra care before charging your vehicle.",
      "test": "Test",
      "gfcitest": "GFCI Self Test:",
      "disabled": "Disabled",
      "gndmon": "Ground Monitoring:",
      "stckctdet": "Stuck Contact Detection:",
      "tempmon": "Temperature Monitoring:",
      "diodechk": "Diode Check:",
      "ventrq": "Vent Required:",
      "count": "Count",
      "gfci": "GFCI:",
      "nognd": "No Ground:",
      "stkct": "Stuck Contact:",
      "hardware": "Hardware",
      "firmware": "Firmware:",
      "openevsewifi": "OpenEVSE WiFi",
      "fwconf": "Firmware config:",
      "fwver": "Firmware version:",
      "espinfo": "ESP info:",
      "flashsz": "Flash Size:",
      "freeram": "Free RAM:",
      "evsettings": "Vehicle Settings",
      "evpause": "Pause status",
      "evpausedesc": "Some vehicles will shutdown if left in sleep mode (pilot signal enable) and then can not be woken up by timers/PV divert. Changing the pause state to disable should resolve this issue, however this removes the ability for the charger to detect if a vehicle is connected when paused.",
      "sleep": "Sleep",
      "display": "Display",
      "simple": "Simple",
      "advanced": "Advanced",
      "brightness": "LED Brightness:",
      "history": "History",
      "type": "Type",
      "loadmore": "Load more",
      "rapicom": "RAPI Command:",
      "send": "Send",
      "rapigetcom": "RAPI Get Commands",
      "get": "Get",
      "description": "Description",
      "read": "Read",
      "rapisetcom": "RAPI Set Commands",
      "rapisysfunc": "RAPI System Functions",
      "function": "Function",
      "none": "None",
      "tesla": "Tesla",
      "selectevcon": "Select the vehicle connection type",
      "accesstoken": "Access Token",
      "reftoken": "Refresh token",
      "teslalogindesc1": "The Tesla login may break from time-to-time as Tesla change their login API, hopefully OpenEVSE will be able to resolve the issue on ",
      "teslalogindesc2": "our server",
      "teslalogindesc3": "but should the login fail you can use a 3rd Party app to generate the appropriate tokens.",
      "teslalogindesc4": "These can be entered in the `Advanced` section as an alternative method of logging in.",
      "apple": "Apple",
      "android": "Android",
      "evfetching": "Fetching vehicle info ...",
      "ovms": "Open Vehicle Monitoring System",
      "soctopic": "State of Charge topic:",
      "socdesc": "The battery level of charge as a percentage",
      "rangetopic": "Range topic:",
      "km": "km",
      "miles": "miles",
      "rangedesc": "The range (on electric) of the vehicle based on the current battery level",
      "timetopic": "Time to charge topic:",
      "timedesc": "The time until the battery is fully charged in seconds",
      "login": "Login",
      "logout": "Logout",
      "battlvl": "Battery Level:",
      "battrng": "Battery Range:",
      "timefchg": "Time to full charge:",
      "http": "HTTP",
      "httppush": "HTTP Push (Always Active)",
      "httppushinfo": "To update manually vehicle data, send HTTP POST request to:",
      "httppushinfo2": "containing json data in body:"

    }
  },
  "fr": {
    "translation": {
      "openevse": "OpenEVSE",
      "loading": "Chargement, veuillez patienter...",
      "language": "Langue",
      "system": "Système",
      "services": "Services",
      "vehicle": "VE",
      "saving": "Sauvegarde",
      "saved": "Sauvegardé",
      "save": "Sauvegarder",
      "wifisetup": "Configuration Wifi",
      "mode": "Mode:",
      "ip": "Addresse IP",
      "sfpackets": "Trames transmises:",
      "rapipackets": "Trames RAPI:",
      "network": "Réseau",
      "rssi": "RSSI dBm",
      "changewifi": "Changer de réseau WiFi",
      "of": " sur ",
      "connect2net": "Se connecter au réseau:",
      "poffaccesspoint": "Fermer le point d'accès",
      "scanning": "Scan en cours...",
      "ssid": "SSID:",
      "passkey": "Clef Wifi",
      "showpass": "Voir le mot de passe",
      "connect": "Connecter",
      "connecting": "Connection au réseau WIFI...",
      "administration": "Administration",
      "username": "Utilisateur:",
      "15max": "15 charactères max",
      "31max": "31 charactères max",
      "password": "Mot de passe:",
      "showpassword": "Voir le mot de passe",
      "httpauth": "Authentication HTTP de l'interface web.",
      "wififirmware": "Firmware module WiFi",
      "version": "Version: ",
      "update": "Mettre à jour",
      "updating": "Mise à jour...",
      "error": "Erreur",
      "complete": "Mise à jour du firmware OK",
      "restart": "Redémarrer",
      "restarting": "Redémarrage...",
      "reset": "Réinitialiser",
      "resetting": "Réinitialisation",
      "advsettings": "Configuration avancée",
      "hostname": "Nom d'hôte:",
      "ntpserver": "Serveur NTP:",
      "rfid": "RFID",
      "enabled": "Activé",
      "rfidnotfound": "Lecteur RFID non trouvé",
      "rfidregistered": "Badges enregistrés",
      "remove": "Retirer",
      "rfidclear": "Supprimer tout",
      "rfidmanage": "Gérer les badges scannés",
      "rfidscan": "Scanner",
      "rfidplace": "Placer votre badge RFID sur le lecteur... ",
      "waiting": "En attente",
      "rfidscanned": "Basge scanné avec succès!",
      "rfiduid": "UID",
      "rfidalregistered": "Ce badge est déjà enregistré",
      "rfidnotregistered": "Ce badge n'est pas enregistré",
      "rfidregister": "Enregistrer le badge",
      "rfidremove": "Retirer le badge",
      "devmode": "Mode Développeur",
      "serialconsoles": "Consoles",
      "debug": "Debug",
      "emoncms": "Supervision Energétique",
      "emoncmsenable": "Activer Emoncms",
      "emoncmsserver": "Serveur Emoncms*:",
      "emoncmsnode": "Noeud Emoncms*:",
      "emoncmsapi": "clef api (écriture) Emoncms*:",
      "emoncmsssltitle": "Emoncms SSL SHA-1 Fingerprint (optionnel):",
      "emoncmshttps": "HTTPS sera activé si présent:",
      "connected": "Connecté:",
      "yes": "oui",
      "no": "non",
      "emoncmssuccess": "Publications réussies:",
      "mqtt": "MQTT",
      "mqttenable": "Activer MQTT",
      "mqttstatuspub": "Status publié sur:",
      "mqttstatusval": "{topic-base}/{status} valeur",
      "mqttrapi": "RAPI par MQTT est obsolète. Veuillez utiliser l'API /claim /override",
      "host": "Hôte*:",
      "port": "Port*:",
      "rejectcert": "Rejeter les certificats auto-signés:",
      "warning": "Attention!!",
      "mqttcerts": "La validation des certificats esst désactivée. Bien que la connection au serveur MQTT soit encryptée, elle est vulnérable à une attaque MITM.",
      "blank": " vide - pas d'authentication",
      "basetopic": "Sujet principal*:",
      "retain": "Conserver les données publiées (retain)",
      "voltagetop": "Sujet Tension:",
      "voltagedesc": "Sujet MQTT pour la Tension afin d'améliorer le calcul de la puissance.",
      "shaper": "Gestion Dynamique du Courant",
      "shaperenable": "Activer la gestion dynamique du courant",
      "shaperdesc": "Module le courant de charge en fonction des capacités de votre abonnement et de la puissance disponible.<br>",
      "shapermaxpow": "Puissance Max authorisée (en W):",
      "shaperlivepow": "Sujet MQTT Puissance instantanée compteur (en W):",
      "ohm": "OhmConnect",
      "ohmenable": "Activer OhmConnect",
      "ohmclick": "Inscription",
      "ohmdesc": "OhmConnect supervise en temps réel les conditions sur le réseau électrique. Quand les centrales les plus polluantes ou que la charge est trop elevée, nos utilisateurs reçoivent une notification afin de sauvegarder l'energie.",
      "ohmhour": "Status Ohm:",
      "ohmkey": "Clef Ohm:",
      "ohmusa": "USA - Californie seulement",
      "ohmkeydesc": "La clef Ohm peut être obtenue sur votre compte OhmConnect, aller dans Settings et trouver le lien \"Open Source Projects\"<br/>Example: https://login.ohmconnect.com/verify-ohm-hour/OpnEoVse",
      "key": "Clef:",
      "divert": "Gestion de production Solaire",
      "divertenable": "Activer la gestion de production Solaire",
      "nomqtt": "MQTT n'est pas activé",
      "nomqttdesc": "Vous devez activer MQTT depuis l'onglet <a href=\"#services\">Services</a>.",
      "divertnomqttdesc": "La gestion de production Solaire nécessite un sujet MQTT contenant la production solaire (SolarPV-gen) ou déficit/excédent du réseau (+I/-E)",
      "divertdesc1": "Ajuste dynamiquement la puissance de charge en fonction de la production solaire ou excédent d'énergie ( export sur le réseau )",
      "divertdesc2": "Si seul la valeur de production solaire est disponible: le courant de charge est modulé selon le total de <b>production solaire</b>.",
      "divertdesc3": "Si le déficit/excédent (+Import/-Export) est disponible, le courant de charge sera modulé selon l'<b>excédent</b>.",
      "divertdesc4": "Si l'EVSE est en pause: la charge débutera quand la production Solaire ou l'excédent de puissance > puissance de charge minimale (min charge rate)",
      "divertdesc5": "La charge se mettra en pause si l'excédent de puissance tombe sous la puissance de charge minimale.",
      "divertnote": "Note: La puissance consommée par l'EVSE est inclue dans le flux d'excédent/déficit",
      "divertsolar": "Solaire",
      "divertgrid": "Import/Export réseau:",
      "chargerate": "Courant de charge:",
      "divertfeed": "Sujet MQTT*:",
      "divertsolar2": "Prod Solaire",
      "divertgrid2": "Réseau (+I/-E)",
      "divertsolar2desc": "Sujet MQTT de la production solaire pour moduler la charge en fonction de la production",
      "divertgrid2desc": "Sujet MQTT import / export (+I/-E) réseau pour moduler la charge en fonction de l'<b>excédent de puissance</b>",
      "divertpvpratio": "Ratio de puissance PV requise:",
      "divertpvpratiodesc": "Ratio de courant PV suffisant pour démarrer la charge ou augmenter le courant.",
      "divertsmoothatt": "Lissage augmentation du détournement:",
      "divertsmoothattdesc": "Le montant de la nouvelle valeur reçue à ajouter à la moyenne de puissance disponible",
      "divertsmoothdec": "Lissage diminution du détournement:",
      "divertsmoothdecdesc": "Le montant de la nouvelle valeur reçue à retirer de la moyenne de puissance disponible",
      "divertmintime": "Temps de charge minimum:",
      "divertmintimedesc": "Le minimum de temps de charge (secondes) une fois activé via le détournement Solaire. Cela peut aider à limiter l'usure du relai",
      "divertwait": "En attente de production solaire",
      "divertcharge": "Charge depuis la production solaire",
      "ocpp": "OCPP 1.6",
      "ocppenable": "Activer OCPP",
      "ocppserver": "URL du Système Central*:",
      "ocppserverhint": "p.ex.: wss://ocpp.example.com/steve/websocket/CentralSystemService",
      "ocppid": "ID du Chargeur*:",
      "ocppacccont": "Contrôle d'accès:",
      "ocppsuspend": "OCPP peut suspendre l'EVSE",
      "ocppenergize": "OCPP peut alimenter la prise",
      "ocppauthkey": "Clef WebSocket (Profil de Sécurité 2):",
      "ocppauth": "Autorisation de Charge:",
      "ocppauthauto": "Autorisation automatique",
      "ocppauthoffline": "Omettre l'autorisation si hors ligne",
      "evseerror": "Erreur EVSE",
      "evseerrordesc1": "OpenEVSE ne répond pas ou n'est pas connecté",
      "status": "Status",
      "current": "Courant",
      "temp": "Temp",
      "energy": "Energie",
      "elapsed": "Ecoulé",
      "evnocon": "VE non connecté",
      "evcon": "VE connecté",
      "active": "Actif:",
      "voltage": "Tension:",
      "avcur": "Courant Disponible:",
      "smcur": "Courant Lissé:",
      "mintimerem": "Temps restant min:",
      "curevent": "Evènement Courant:",
      "nxtevent": "Evènement Suivant:",
      "modenml": "Normal (rapide)",
      "modeeco": "Eco (solaire)",
      "chargeopt": "Options de Charge",
      "manoverride": "Contrôle Manuel",
      "start": "Démarrer",
      "pause": "Pause",     //Missing translation
      "stop": "Arrêter",
      "clear": "Libérer",
      "timelimit": "Limite de Temps:",
      "energylimit": "Limite d'Energie:",
      "timer": "Minuteur:",
      "delaydesc1": "Un décalage aléatoire de +/-",
      "delaydesc2": "minutes sera appliquée au temps de départ afin d'éviter les pics de charge sur le réseau.",
      "delayadj": "Ajustement du démarrage aléatoire:",
      "seconds": "secondes",
      "set": "Ajouter",
      "cancel": "Supprimer",
      "starting": "Starting",     //Missing translation
      "session": "Session Courante:",
      "total": "Total:",
      "sensorval": "Données Capteurs",
      "sensor": "Capteur",
      "value": "Valeur",
      "pilot": "Consigne:",
      "curnow": "Courant Instantané:",
      "setup": "Paramètres",
      "rtc": "Horloge: Aucun RTC detecté",
      "time": "Date/Heure",
      "timezone": "Fuseau horaire:",
      "settimefrom": "Régler l'heure depuis",
      "settime": "Set time",     //No translation
      "manual": "Manuel",
      "browser": "Navigateur",
      "ntp": "NTP",
      "servicelev": "Niveau de Service:",
      "maxcur": "Courant max:",
      "name": "Nom",
      "level": "Niveau",
      "min": "Minimum:",
      "max": "Maximum:",
      "ssrscale": "Echelle Capteur:",
      "ssroff": "Décalage Capteur:",
      "safety": "Sécurité",
      "safetydesc": "Vérification de sécurité du matériel. Activer le mode dev (Système > Mode Développeur) pour activer/désactiver ou utiliser le menu LCD/bouton.",
      "safetywarn": "Tous les tests de sécurité ne sont pas activés, veuillez être vigilant avant de charger votre véhicule.",
      "test": "Test",
      "gfcitest": "autotest GFCI:",
      "disabled": "Disabled",     //No translation
      "gndmon": "Contrôle de la Terre:",
      "stckctdet": "Détection Relai Collé:",
      "tempmon": "Contrôle de la T°:",
      "diodechk": "Vérification Diode:",
      "ventrq": "Ventilation requise:",
      "count": "Total",
      "gfci": "GFCI:",
      "nognd": "Problème Terre:",
      "stkct": "Relai Collé:",
      "hardware": "Matériel",
      "firmware": "Micrologicel:",
      "openevsewifi": "OpenEVSE WiFi",
      "fwconf": "Config Firmware:",
      "fwver": "version Firmware:",
      "espinfo": "info ESP:",
      "flashsz": "Espace Flash:",
      "freeram": "RAM disponible:",
      "evsettings": "Paramètres VE",
      "evpause": "Mode de Pause",
      "evpausedesc": "Certains véhicules vont s'éteindre si laissé en mode Veille (signal pilote activé) et ne peuvent ensuite être réveillés par un minuteur ou production solaire. Changer l'état de Pause en Inactif devrait résoudre ce problème. Cependant cela retire la possibilité au chargeur de détecter si le véhicule est connecté pendant la Veille.",
      "sleep": "Veille",
      "display": "Affichage",
      "simple": "Simple",
      "advanced": "Avancé",
      "brightness": "Luminosité LED:",
      "history": "Historique",
      "type": "Type",
      "loadmore": "Charger plus",
      "rapicom": "RAPI Command:",     //No translation
      "send": "Send",     //No translation
      "rapigetcom": "RAPI Get Commands",     //No translation
      "get": "Get",     //No translation
      "description": "Description",     //No translation
      "read": "Read",     //No translation
      "rapisetcom": "RAPI Set Commands",     //No translation
      "rapisysfunc": "RAPI System Functions",     //No translation
      "function": "Function",     //No translation
      "none": "Aucun",
      "tesla": "Tesla",
      "selectevcon": "Selectionner le type de connection au véhicule",
      "accesstoken": "Token d'accès",
      "reftoken": "Renouveller le Token",
      "teslalogindesc1": "L'identification Tesla peut cesser de fonctionner de temps en temps quand Tesla change son API, heureusement OpenEVSE sera capable de résoudre le problème sur ",
      "teslalogindesc2": "nos serveurs",
      "teslalogindesc3": "mais si elle échoue, vous pouvez utiliser une application externe pour générer le token approprié.",
      "teslalogindesc4": "Celui-ci peut être configuré dans la section `Avancé` comme méthode alternative d'authentification.",
      "apple": "Apple",
      "android": "Android",
      "evfetching": "Récupération des données du véhicule ...",
      "ovms": "Open Vehicle Monitoring System",
      "soctopic": "Sujet MQTT Etat de Charge (SOC):",
      "socdesc": "Niveau de batterie en %",
      "rangetopic": "Sujet MQTT Autonomie:",
      "km": "km",
      "miles": "miles",
      "rangedesc": "L'autonomie du véhicule basée sur le niveau de charge de la batterie",
      "timetopic": "Sujet MQTT Temps de Charge restant:",
      "timedesc": "Le temps restant jusqu'à la charge complète en secondes",
      "login": "Connecter",
      "logout": "Déconnecter",
      "battlvl": "Niveau Batterie:",
      "battrng": "Autonomie Batterie:",
      "timefchg": "Temps de charge complète restant:",
      "http": "HTTP",
      "httppush": "Push HTTP (Toujours actif)",
      "httppushinfo": "Pour mettre à jours manuellement les données véhicule, envoyer une requête HTTP POST vers:",
      "httppushinfo2": "contenant ce modèle json dans body:"
      
    }
  },
  "hu": {
    "translation": {
      "openevse": "OpenEVSE",
      "loading": "Betöltés, kérem várjon...",
      "language": "Nyelv",
      "system": "Rendszer",
      "services": "Szolgáltatások",
      "vehicle": "Jármű",
      "saving": "Mentés…",
      "saved": "Mentve",
      "save": "Mentés",
      "wifisetup": "Wifi Beállítás",
      "mode": "Mód:",
      "ip": "IP Cím",
      "sfpackets": "Sikeres csomagok:",
      "rapipackets": "RAPI csomagok:",
      "network": "Hálózat",
      "rssi": "RSSI dBm",
      "changewifi": "WiFi hálózat módosítása",
      "of": "  /  ",
      "connect2net": "Csatlakozás a hálózathoz:",
      "poffaccesspoint": "Kapcsolja ki a hozzáférési pontot",
      "scanning": "Beolvasás...",
      "ssid": "Hálózatnév (SSID):",
      "passkey": "Hálózati jelszó:",
      "showpass": "Jelszó megjelenítése",
      "connect": "Csatlakozás",
      "connecting": "Csatlakozás a WIFI hálózathoz...",
      "administration": "Adminisztráció",
      "username": "Felhasználónév:",
      "15max": "max. 15 karakter",
      "31max": "max. 31 karakter",
      "password": "Jelszó:",
      "showpassword": "Jelszó megjelenítése",
      "httpauth": "Webes felület HTTP hitelesítés.",
      "wififirmware": "WiFi Firmware",
      "version": "Verzió: ",
      "update": "Frissítés",
      "updating": "Frissítés...",
      "error": "Hiba",
      "complete": "A firmware frissítése rendben befejeződött.",
      "restart": "Újraindítás",
      "restarting": "Újraindítás...",
      "reset": "Gyári beállítások visszaállítása,",
      "resetting": "Újra beállítás...",
      "advsettings": "Speciális Beállítások",
      "hostname": "Host név:",
      "ntpserver": "NTP Szerver:",
      "rfid": "RFID",
      "enabled": "Engedélyezve",
      "rfidnotfound": "Az olvasó nem található",
      "rfidregistered": "Regisztrált címkék",
      "remove": "Eltávolít",
      "rfidclear": "Címkék törlése",
      "rfidmanage": "A beolvasott címkék kezelése",
      "rfidscan": "Beolvas",
      "rfidplace": "Helyezze RFID címkéjét a szkennerre...",
      "waiting": "Várakozás",
      "rfidscanned": "A címke sikeresen beolvasva!",
      "rfiduid": "UID",
      "rfidalregistered": "A címke már regisztrálva van",
      "rfidnotregistered": "A címke nincs regisztrálva",
      "rfidregister": "Címke regisztrálása",
      "rfidremove": "Címke eltávolítása",
      "devmode": "Fejlesztői mód",
      "serialconsoles": "Soros konzolok",
      "debug": "Hibakeresés",
      "emoncms": "Energia Felügyelet",
      "emoncmsenable": "Emoncms Engedélyezése",
      "emoncmsserver": "Emoncms Szerver*:",
      "emoncmsnode": "Emoncms Node*:",
      "emoncmsapi": "Emoncms write-apikey*:",
      "emoncmsssltitle": "Emoncms SSL SHA-1 Fingerprint (opcionális):",
      "emoncmshttps": "A HTTPS engedélyezve lesz, ha van, például:",
      "connected": "Csatlakoztatva:",
      "yes": "igen",
      "no": "nem",
      "emoncmssuccess": "Sikeres bejegyzések:",
      "mqtt": "MQTT",
      "mqttenable": "MQTT Engedélyezése",
      "mqttstatuspub": "Állapot közzétéve a következőnek:",
      "mqttstatusval": "{base-topic}/{status} érték",
      "mqttrapi": "A RAPI az MQTT felett elavult. Használja a /claim vagy /override API-t",
      "host": "Host*:",
      "port": "Port*:",
      "rejectcert": "Saját aláírású tanúsítványok elutasítása:",
      "warning": "Figyelmeztetés!!",
      "mqttcerts": "A tanúsítvány érvényesítése le van tiltva, bár az MQTT szerverrel való kapcsolat titkosítva lesz, a kapcsolat továbbra is sebezhető a köztes támadásokkal szemben.",
      "blank": " üres – nincs hitelesítés",
      "basetopic": "Alap topic*:",
      "retain": "A közzétett adatok megőrzése",
      "voltagetop": "Feszültség topic:",
      "voltagedesc": "Feszültség MQTT topic a teljesítmény számítások javítása érdekében",
      "shaper": "Dinamikus Áramkezelés",
      "shaperenable": "Dinamikus Áramkezelés Engedélyezése",
      "shaperdesc": "Változtatja a töltőáramot az előfizetése kapacitásának és a rendelkezésre álló teljesítménynek megfelelően.<br>",
      "shapermaxpow": "Maximális engedélyezett teljesítmény (W-ban):",
      "shaperlivepow": "A mérő pillanatnyi teljesítménye MQTT topic (W-ban):",
      "ohm": "OhmConnect",
      "ohmenable": "OhmConnect Engedélyezése",
      "ohmclick": "Kattintson ide a csatlakozáshoz",
      "ohmdesc": "Az OhmConnect valós idejű állapotokat figyel az elektromos hálózaton. Amikor piszkos és nem fenntartható erőművek kapcsolnak be, felhasználóink értesítést kapnak az energiatakarékosság érdekében.",
      "ohmhour": "Ohm Hour:",
      "ohmkey": "Ohm Key:",
      "ohmusa": "USA - California csak",
      "ohmkeydesc": "Az Ohm Key az OhmConnectbe való bejelentkezéssel érhető el, lépjen be a Beállításokba és keresse meg a hivatkozást az \Open Source Projects\ részben.<br/>Például: https://login.ohmconnect.com/verify-ohm-hour/OpnEoVse",
      "key": "Key:",
      "divert": "Solar PV átirányítás",
      "divertenable": "Solar PV Átirányítás Engedélyezése",
      "nomqtt": "Az MQTT nincs engedélyezve.",
      "nomqttdesc": "Engedélyeznie kell az MQTT-t a <a href=\"#services\">Szolgáltatások</a> lapon.",
      "divertnomqttdesc": "Solar PV Átirányításhoz 'Solar PV' vagy 'Hálózat (+I/-E)' táplálásra van szükség amelyet MQTT-n keresztül kell biztosítani.",
      "divertdesc1": "Dinamikusan állítsa be a töltő áramot a napelemes PV-termelés vagy a többletenergia alapján (hálózati export).",
      "divertdesc2": "Ha csak a napelemes termelés áll rendelkezésre: a töltő áram a <b>napelemes PV-termelés</b> alapján módosul.",
      "divertdesc3": "Ha rendelkezésre áll a hálózati többletteljesítmény +I/-E (pozitív Import / negatív Export): a töltő áram módosítása a rendelkezésre álló <b>többletteljesítmény</b> alapján.",
      "divertdesc4": "Ha az EVSE alvó állapotban van: a töltés akkor kezdödik, amikor a napelemes PV / töblet teljesítmény > szükséges PV teljesítmény arány.",
      "divertdesc5": "A töltés leáll, ha a többletteljesítmény egy ideig a minimális töltési áram alá csökken.",
      "divertnote": "Megjegyzés: Feltételezzük, hogy az EVSE teljesítménye benne van a hálózati betáplálásban",
      "divertsolar": "Solar:",
      "divertgrid": "Hálózat +Import/-Export:",
      "chargerate": "Töltési arány:",
      "divertfeed": "Táplál*:",
      "divertsolar2": "Solar PV",
      "divertgrid2": "Hálózat (+I/-E)",
      "divertsolar2desc": "Solar PV MQTT topic a töltő áram módosítása a napenergia termelés alapján.",
      "divertgrid2desc": "Hálózat (+I/-E) MQTT topic a töltő áram módosítása a <b>többletteljesítmény</b> alapján.",
      "divertpvpratio": "Szükséges PV teljesítmény arány:",
      "divertpvpratiodesc": "A PV áram azon része, amely elegendő a töltés megkezdéséhez vagy az áram növeléséhez",
      "divertsmoothatt": "Az átírányítás simított emelése:",
      "divertsmoothattdesc": "Az új betáplálási érték összege, amelyet hozzá kell adni az átirányítási rendelkezésre álló teljesítmény gördülő átlagához",
      "divertsmoothdec": "Az átírányítás simított csökkentése:",
      "divertsmoothdecdesc": "Az új betáplálási érték összege, amelyet ki kell vonni az átirányítási rendelkezésre álló teljesítmény gördülő átlagából.",
      "divertmintime": "Minimális töltési idő:",
      "divertmintimedesc": "Az a minimális idő (másodpercben), amíg az autót tölteni kell, miután engedélyezték a Solar PV átirányításon keresztül. Ez segíthet minimalizálni az EVSE kopását.",
      "divertwait": "Napenergiára várva",
      "divertcharge": "Töltés napenergából",
      "ocpp": "OCPP 1.6",
      "ocppenable": "OCPP Engedélyezése",
      "ocppserver": "Központi Rendszer URL*:",
      "ocppserverhint": "például: wss://ocpp.example.com/steve/websocket/CentralSystemService",
      "ocppid": "Töltődoboz Azonosítója*:",
      "ocppacccont": "Hozzáférés Szabályozás:",
      "ocppsuspend": "Az OCPP felfüggesztheti az EVSE-t",
      "ocppenergize": "Az OCPP feszültség alá helyezheti a dugót",
      "ocppauthkey": "WebSocket kulcs (2. biztonsági profil):",
      "ocppauth": "Töltés Engedélyezés:",
      "ocppauthauto": "Automatikus engedélyezés",
      "ocppauthoffline": "Az engedélyezés kihagyása offline állapotban",
      "evseerror": "EVSE Hiba",
      "evseerrordesc1": "Az OpenEVSE nem válaszol vagy nem csatlakozik",
      "status": "Állapot",
      "current": "Áram",
      "temp": "Hőfok",
      "energy": "Energia",
      "elapsed": "Eltelt idő",
      "evnocon": "EV nincs csatlakoztatva",
      "evcon": "EV csatlakoztatva",
      "active": "Aktív:",
      "voltage": "Feszültség:",
      "avcur": "Elérhető Áram:",
      "smcur": "Simított Áram:",
      "mintimerem": "Minimális hátralévő idő:",
      "curevent": "Aktuális Esemény:",
      "nxtevent": "Következő Esemény:",
      "modenml": "Normál (gyors)",
      "modeeco": "Eco (PV átirányítás)",
      "chargeopt": "Töltési Lehetőségek",
      "manoverride": "Kézi Felülírás",
      "start": "Indítás",
      "pause": "Szünet",
      "stop": "Megáll",
      "clear": "Törlés",
      "timelimit": "Idő Korlátozás:",
      "energylimit": "Energia Korlátozás:",
      "timer": "Időzítés:",
      "delaydesc1": "A rendszer egy +/-",
      "delaydesc2": "perces véletlenszerű késleltetést alkalmaz a kezdési időpontra, hogy megakadályozza a hálózat hirtelen terhelésnövekedését.",
      "delayadj": "Véletlenszerű indítás beállítása:",
      "seconds": "másodperc",
      "set": "Beállít",
      "cancel": "Töröl",
      "starting": "Elindulás",
      "session": "Ez a töltés:",
      "total": "Összes töltés:",
      "sensorval": "Érzékelő Értékek",
      "sensor": "Érzékelő",
      "value": "Érték",
      "pilot": "Alapjel:",
      "curnow": "Áram Most:",
      "setup": "Beállítás",
      "rtc": "Idő: Nem észlelhető RTC",
      "time": "Dátum / Óra",
      "timezone": "Időzóna:",
      "settimefrom": "Idő beállítása innen",
      "settime": "Idő beállítása",
      "manual": "Kézi",
      "browser": "Böngésző",
      "ntp": "NTP",
      "servicelev": "Szolgáltatás Szintje:",
      "maxcur": "Maximális áramerősség:",
      "name": "Név",
      "level": "Level",
      "min": "Minimum:",
      "max": "Maximum:",
      "ssrscale": "Érzékelő skála:",
      "ssroff": "Érzékelő eltolás:",
      "safety": "Biztonság",
      "safetydesc": "Hardverbiztonsági ellenőrzések. Engedélyezze a fejlesztői módot (Rendszer > Fejlesztői mód) az engedélyezéshez/letiltáshoz vagy használja a fizikai LCD + menü gombot.",
      "safetywarn": "Nincs minden biztonsági teszt engedélyezve, Kérjük, járjon el fokozott figyelemmel a jármű töltése előtt.",
      "test": "Teszt",
      "gfcitest": "GFCI Önteszt:",
      "disabled": "Letiltva",
      "gndmon": "Földelés Figyelés:",
      "stckctdet": "Beragadt Kontaktus Érzékelés:",
      "tempmon": "Hőmérséklet Figyelés:",
      "diodechk": "Dióda Ellenőrzés:",
      "ventrq": "Szellőztetés Szükséges:",
      "count": "Számláló",
      "gfci": "GFCI:",
      "nognd": "Nincs Földelés:",
      "stkct": "Beragadt Kontaktus:",
      "hardware": "Hardver",
      "firmware": "Firmware:",
      "openevsewifi": "OpenEVSE WiFi",
      "fwconf": "Firmware konfiguráció:",
      "fwver": "Firmware verzió:",
      "espinfo": "ESP információ:",
      "flashsz": "Flash mérete:",
      "freeram": "Szabad RAM:",
      "evsettings": "Jármű Beállítások",
      "evpause": "Állapot szüneteltetése",
      "evpausedesc": "Egyes járművek leállnak, ha alvó üzemmódban maradnak (pilot jel engedélyezés), és nem ébreszthetők fel időzítőkkel / PV átirányítással. A szünet állapotának letiltásra történő módosítása megoldja ezt a problémát, azonban ezzel megszűnik a töltő azon képessége, hogy észlelje, ha egy jármű csatlakozik, amikor szünetel.",
      "sleep": "Alvás",
      "display": "Kijelzés",
      "simple": "Egyszerű",
      "advanced": "Haladó",
      "brightness": "LED Fényerő:",
      "history": "Előzmények",
      "type": "Típus",
      "loadmore": "Töltsön be többet",
      "rapicom": "RAPI Parancs:",
      "send": "Elküld",
      "rapigetcom": "RAPI Kérés Parancsok",
      "get": "Kérés",
      "description": "Leírás",
      "read": "Olvas",
      "rapisetcom": "RAPI Beállítás Parancsok",
      "rapisysfunc": "RAPI Rendszerfunkciók",
      "function": "Funkció",
      "none": "Egyik sem",
      "tesla": "Tesla",
      "selectevcon": "Válassza ki a jármű csatlakozási típusát",
      "accesstoken": "Hozzáférési token",
      "reftoken": "Token frissítése",
      "teslalogindesc1": "A Tesla bejelentkezés időről időre megszakadhat, mivel a Tesla megváltoztatja a bejelentkezési API-ját, remélhetőleg az OpenEVSE meg tudja majd oldani a problémát",
      "teslalogindesc2": "a szerverünk",
      "teslalogindesc3": "de ha a bejelentkezés sikertelen, használhat egy harmadik féltől származó alkalmazást a megfelelő token létrehozásához.",
      "teslalogindesc4": "Ezeket a `Speciális` részben lehet beírni alternatív bejelentkezési módként.",
      "apple": "Apple",
      "android": "Android",
      "evfetching": "Járműadatok lekérése ...",
      "ovms": "Open Vehicle Monitoring System",
      "soctopic": "Töltési Állapot topic:",
      "socdesc": "Az akkumulátor töltöttségi szintje százalékban",
      "rangetopic": "Hatótávolság topic:",
      "km": "km",
      "miles": "mérföld",
      "rangedesc": "A jármű (elektromos) hatótávolsága az akkumulátor aktuális töltöttségi szintje alapján",
      "timetopic": "Töltési idő topic:",
      "timedesc": "Az akkumulátor teljes feltöltődéséig eltelt idő másodpercben",
      "login": "Bejelentkezés",
      "logout": "Kijelentkezés",
      "battlvl": "Akkumulátor Töltöttség:",
      "battrng": "Akkumulátor Hatótáv:",
      "timefchg": "A teljes feltöltés ideje:",
      "http": "HTTP",
      "httppush": "HTTP Push (Mindig Aktív)",
      "httppushinfo": "A járműadatok kézi frissítéséhez küldjön HTTP POST kérést a következő címre:",
      "httppushinfo2": "json adatokat tartalmaz a törzsben:"

    }
  },
}, "en", ko);
